import type { ArrangementDoc } from '../types';

const CLASSIC_PRZYD_TEMPLATE: ArrangementDoc = {
  schema_version: '1.0',
  id: 'template-classic-prydz',
  type: 'template',
  title: 'Classic Prydz',
  style: 'prog_house',
  reference_artists: ['Eric Prydz (Pryda)', 'Cirez D'],
  bpm: 126,
  bpm_range: [122, 128],
  swing_percent: 2,
  ghost_note_density: 1,
  rows: [
    'Kick',
    'Sub/Bass',
    'Pluck/Arp',
    'Lead',
    'Pads/Strings',
    'Vox',
    'Perc/Hats',
    'FX/Risers',
  ],
  total_bars: 176,
  sections: [
    // ── Intro: bars 1–32 ──────────────────────────────────
    {
      id: 'intro',
      name: 'Intro',
      color: 'gray',
      start_bar: 1,
      bars: 32,
      activity: {
        Kick: [0, 0, 1, 1],
        'Sub/Bass': [0, 0, 0, 0],
        'Pluck/Arp': [1, 1, 1, 1],
        Lead: [0, 0, 0, 0],
        'Pads/Strings': [2, 2, 2, 2],
        Vox: [0, 0, 0, 0],
        'Perc/Hats': [1, 1, 1, 1],
        'FX/Risers': [1, 1, 1, 1],
      },
      notes: [
        'Open with a warm pad wash — minor key, slow attack, long reverb tail. Sets the emotional tone before anything rhythmic hits.',
        'Bar 17: bring the kick in with a low-pass filter sweep over 4 bars. The kick should feel distant, not present.',
        'Signature Prydz arp starts subtle at bar 1 — keep it low in the mix, just enough to hint at the harmonic progression.',
        'Light shaker on the off-beats from bar 1. No closed hi-hats yet — keep it sparse.',
      ],
      references: [
        {
          artist: 'Eric Prydz',
          title: 'Opus',
          start_seconds: 0,
          end_seconds: 64,
          note: 'Reference intro pad and atmospheric build.',
        },
      ],
    },
    // ── Build 1: bars 33–64 ────────────────────────────────
    {
      id: 'build-1',
      name: 'Build 1',
      color: 'amber',
      start_bar: 33,
      bars: 32,
      activity: {
        Kick: [3, 3, 3, 3],
        'Sub/Bass': [1, 1, 2, 3],
        'Pluck/Arp': [1, 2, 2, 3],
        Lead: [0, 0, 1, 1],
        'Pads/Strings': [3, 3, 3, 3],
        Vox: [1, 1, 1, 1],
        'Perc/Hats': [2, 2, 2, 2],
        'FX/Risers': [1, 2, 2, 3],
      },
      notes: [
        'Full kick from bar 33 — this is where the track starts to lock in. Open hats join at bar 33 for energy.',
        'Bass-line enters filtered at bar 33, opens up over the section. Keep the sub rolling 16th notes, side-chained to the kick.',
        'Bar 49: lead synth enters with a melodic motif. Keep it mid-range, not yet the main hook — tease it.',
        'Chopped vocal one-shot from bar 49 (e.g. a synth-vocal phrase, not a full lyric). Repeat every 4 bars, add reverb tail.',
        'FX riser starts at bar 57, gains intensity each bar. White noise + reverb automation + filter sweep to peak at bar 64.',
      ],
      references: [
        {
          artist: 'Eric Prydz',
          title: 'Pjanoo',
          start_seconds: 64,
          end_seconds: 128,
          note: 'Classic build structure — how elements enter one by one.',
        },
      ],
    },
    // ── Drop 1: bars 65–96 ─────────────────────────────────
    {
      id: 'drop-1',
      name: 'Drop 1',
      color: 'red',
      start_bar: 65,
      bars: 32,
      activity: {
        Kick: [3, 3, 3, 3],
        'Sub/Bass': [3, 3, 3, 3],
        'Pluck/Arp': [3, 3, 3, 3],
        Lead: [3, 3, 3, 3],
        'Pads/Strings': [2, 2, 2, 2],
        Vox: [3, 3, 3, 3],
        'Perc/Hats': [3, 3, 3, 3],
        'FX/Risers': [1, 1, 1, 1],
      },
      notes: [
        'The main drop — all elements hit at full intensity. The hook (lead + arp) carries the energy.',
        'Prydz signature: the drop is a continuation, not a reset. The lead melody from Build 1 becomes the full main hook.',
        'Vocal chop hits every bar for the first 16 bars, then every 2 bars — creates variation within the full section.',
        'Keep FX minimal — only impact hits on the 1 of every 8-bar phrase. No risers during the drop; let the groove breathe.',
        'Sub bass is the anchor — tight side-chain to kick, no sustain bleeding into the next bar.',
      ],
      references: [
        {
          artist: 'Eric Prydz',
          title: 'Generate',
          start_seconds: 80,
          end_seconds: 144,
          note: 'Reference drop energy and how the hook sits over full percussion.',
        },
      ],
    },
    // ── Breakdown: bars 97–128 ─────────────────────────────
    {
      id: 'breakdown',
      name: 'Breakdown',
      color: 'blue',
      start_bar: 97,
      bars: 32,
      activity: {
        Kick: [0, 0, 1, 1],
        'Sub/Bass': [0, 0, 0, 0],
        'Pluck/Arp': [1, 1, 2, 2],
        Lead: [3, 3, 3, 3],
        'Pads/Strings': [3, 3, 3, 3],
        Vox: [2, 2, 2, 2],
        'Perc/Hats': [1, 1, 1, 1],
        'FX/Risers': [2, 2, 2, 2],
      },
      notes: [
        'Kick drops out at bar 97. Let the reverb tail ring out for 2 bars before the pads take over entirely.',
        'Lead melody takes centre stage — this is the emotional peak of the track. Use a different lead patch if possible (warmer, more sustain).',
        'Bar 113: kick returns with a band-pass filter, just the thud. No hats, no percussion — just kick + pads + vocal.',
        'Cinematic swell on the pads starting bar 113 — automate filter cutoff + volume up to bar 128. FX build underneath.',
        'Vocal phrase or shimmer verb on the lead to carry the breakdown\'s emotional arc. Delays should be dotted 8th or 1/4 note.',
      ],
      references: [
        {
          artist: 'Eric Prydz',
          title: 'Opus',
          start_seconds: 200,
          end_seconds: 280,
          note: 'Reference breakdown — how the emotional arc builds over 32 bars.',
        },
      ],
    },
    // ── Build 2: bars 129–144 ──────────────────────────────
    {
      id: 'build-2',
      name: 'Build 2',
      color: 'amber',
      start_bar: 129,
      bars: 16,
      activity: {
        Kick: [3, 3],
        'Sub/Bass': [1, 3],
        'Pluck/Arp': [3, 3],
        Lead: [3, 3],
        'Pads/Strings': [3, 3],
        Vox: [3, 3],
        'Perc/Hats': [2, 3],
        'FX/Risers': [3, 3],
      },
      notes: [
        'Short build — only 16 bars. All elements come back in the first 8 bars. No time for teasing; get to the energy.',
        'Snare roll on the 8th note starting at bar 137 (bar 9 of the build), with a final crash at bar 144.',
        'White noise riser throughout the entire build — start low-passed, open fully at bar 144. Layer a reversed cymbal for impact.',
      ],
      references: [],
    },
    // ── Drop 2: bars 145–160 ───────────────────────────────
    {
      id: 'drop-2',
      name: 'Drop 2',
      color: 'red',
      start_bar: 145,
      bars: 16,
      activity: {
        Kick: [3, 3],
        'Sub/Bass': [3, 3],
        'Pluck/Arp': [3, 3],
        Lead: [3, 3],
        'Pads/Strings': [2, 2],
        Vox: [3, 3],
        'Perc/Hats': [3, 3],
        'FX/Risers': [1, 1],
      },
      notes: [
        'Same energy as Drop 1 but condensed to 16 bars — hits harder, shorter shelf life. Keeps the listener engaged.',
        'No need for the full 32-bar repetition. Variation comes from a slight change in the lead melody or an extra vocal layer.',
        'Maintain the same kick pattern but add a 2-bar fill every 8 bars (bar 151: extra open hat, bar 159: snare fill).',
      ],
      references: [],
    },
    // ── Outro: bars 161–176 ────────────────────────────────
    {
      id: 'outro',
      name: 'Outro',
      color: 'gray',
      start_bar: 161,
      bars: 16,
      activity: {
        Kick: [2, 0],
        'Sub/Bass': [1, 0],
        'Pluck/Arp': [1, 0],
        Lead: [0, 0],
        'Pads/Strings': [2, 0],
        Vox: [1, 0],
        'Perc/Hats': [1, 0],
        'FX/Risers': [2, 2],
      },
      notes: [
        'Gradual fade-out of all elements. Low-pass the kick at bar 161, let it ring with reverb for the first 8 bars, then cut at bar 169.',
        'Lead cuts out immediately at bar 161 — keep the reverb tail ringing.',
        'Pads and arp fade over the first 8 bars. By bar 169 only FX reverb tails should remain.',
        'Final reverb tail on everything — ride it out for the last 8 bars. Long reverb, low volume, slow decay to silence.',
      ],
      references: [],
    },
  ],
  analysis_metadata: null,
};

export default CLASSIC_PRZYD_TEMPLATE;
